examples/example_mnist_grbm.py
examples/example_mnist_hopfield.py
examples/example_mnist_rbm.py
examples/plotting.py
paysage/backends/python_backend/matrix.py
paysage/backends/python_backend/nonlinearity.py
paysage/batch.py
paysage/layers.py
paysage/metrics.py
paysage/models/hidden.py
paysage/models/initialize/init_visible.py
paysage/penalties.py

This PR should put in place most things that are needed to begin working on the PyTorch backend.

Additional Refactoring and Cleanup of the Python Backend

---

docs/index.md
mkdocs.yml

Set up a skeleton for documentation [mkdocs](http://www.mkdocs.org).

Set up skeleton for docs

---

paysage/backends/python_backend/nonlinearity.py
paysage/backends/python_backend/rand.py
paysage/backends/pytorch_backend/nonlinearity.py
paysage/backends/pytorch_backend/rand.py
paysage/models/hidden.py

A few minor cleanup things, plus docstrings for the functions in the nonlinearity and rand backend modules.

More torch backend

---

examples/example_mnist_rbm_sklearn.py

bug fixes in sklearn RBM example

fix missing references to imported utils module

---

paysage/backends/python_backend/matrix.py

Add more complete docstrings to the python_backend matrix.py module.

Docstrings

---

circle.yml
test/test_backends.py

Circle CI should work with pytorch now. Added backend tests to CI.

circle ci working with pytorch / rebased

---

Dockerfile
circle.yml
test/test_backends.py

Avctrh reproducible builds and containerization

---

Dockerfile
circle.yml
test/test_backends.py

- Re-introduce docker functionality (after clearing CI cache).
- Made dot and energy distance tests less stringent to avoid occasional non-deterministic CI failures.
- Added docker to CI process

re-introduce docker functionality & CI tweaks

---

Dockerfile
LICENSE
circle.yml
docs/batch.md
docs/fit.md
docs/hidden.md
docs/init_hidden.md
docs/layers.md
docs/optimizers.md
paysage/layers.py
paysage/models/hidden.py
test/test_backends.py

Clean up a few things in the `model_config` PR and merge in previous updates from `master`

Model config ckf

---

docs/backends.md
docs/batch.md
docs/optimizers.md
paysage/backends/__init__.py
paysage/backends/python_backend/matrix.py
paysage/backends/pytorch_backend/matrix.py
paysage/layers.py
test/test_backends.py

Added some basic matrix functions to the backends: `add`, `subtract`, `multiply`, and `divide` along with tests and documentation. These functions do broadcasting automatically.
Added a function `mapzip` to the backends that is useful for working with iterables like lists and namedtuples.

Common backend functions

---

Dockerfile
paysage/__init__.py
paysage/fit.py
paysage/metrics.py
paysage/models/__init__.py

Unify the API interface for metric classes - all classes have an update() method that takes a value of type MetricState.

Metrics api

---

docs/batch.md
docs/fit.md
docs/init_model.md
docs/model.md
docs/optimizers.md
docs/tap_machine.md
examples/example_mnist_tap_machine.py
examples/example_util.py
paysage/fit.py
paysage/layers.py
paysage/metrics.py
paysage/models/initialize/init_model.py
paysage/models/model.py
paysage/models/tap_machine.py
paysage/optimizers.py
test/paysage/models/test_save_read.py
test/paysage/test_layers.py
test/test_rbm.py

Fix merge conflicts  and clean up.

Stateless layers merge

---

paysage/models/tap_machine.py

Followup to #77: saw @jrwalsh1's comment and figured might as well tidy that before it's forgotten.

Use idiom for checking if in [1, 2, 3]

---

examples/example_mnist_tap_machine.py
paysage/fit.py
paysage/layers.py
paysage/metrics.py
paysage/models/model.py
paysage/models/tap_machine.py
test/paysage/test_layers.py

Deprecate marginal free energy

---

docs/batch.md
docs/fit.md
docs/gradient_util.md
docs/layers.md
docs/metrics.md
docs/model.md
docs/optimizers.md
docs/tap_machine.md
examples/example_mnist_grbm.py
examples/example_mnist_hopfield.py
examples/example_mnist_rbm.py
examples/example_mnist_tap_machine.py
paysage/backends/python_backend/matrix.py
paysage/backends/pytorch_backend/matrix.py
paysage/metrics.py

This PR adds a simple heat capacity metric.  I have not included the TAP3-based heat capacity here since it's not commensurate with this one yet...

Heat capacity

---

paysage/fit.py
paysage/layers.py
paysage/models/gradient_util.py
paysage/models/initialize/init_model.py
paysage/models/model.py

Make whitespace a bit more adherent to pylint/google style conventions, minor edits to make code more explicit and hopefully easier to scan through.

Minor edits

---

examples/example_mnist_grbm.py
examples/example_mnist_hopfield.py
examples/example_mnist_rbm.py
examples/example_mnist_tap_machine.py
paysage/batch.py
test/test_rbm.py
test/test_tap_machine.py

As the title says ... I changed the name of the `Batch` class to `HDFBatch` because it describes more clearly what it is ..

change name from batch to hdfbatch

---

examples/example_mnist_deep_rbm.py
examples/example_mnist_grbm.py
examples/example_mnist_hopfield.py
examples/example_mnist_rbm.py
examples/example_util.py
paysage/fit.py
test/test_rbm.py

Some minor clean up of the `deep_models` branch. Mostly in the examples.

Deep models ckf

---

paysage/backends/python_backend/matrix.py
paysage/backends/pytorch_backend/matrix.py
paysage/layers.py
paysage/models/gradient_util.py
paysage/models/model.py
test/test_backends.py
test/test_derivatives.py

Mostly, I added a few additional backend functions for in place tensor arithmetic, some patterns for creating Gradient objects, and `TODO:` comments where I had questions.

ref-tap cleanup and comments

---

paysage/layers.py
paysage/models/model.py

Ref tap ckf

---

circle.yml
paysage/layers.py
paysage/math_utils.py
paysage/metrics.py
test/paysage/test_math_utils.py

This PR makes the online stats calculations use common objects through more of the code.
- Adds a `MeanCalculator` to `math_utils`
- Uses it in the `metrics`
- Uses the `MeanVarianceCalculator` in `GuassianLayer.online_param_update` (where it makes a couple percent difference for some features in an MNIST test).

Common statistics calculations

---

paysage/layers.py
paysage/models/model.py

This PR fixes a bug where the portion of the gradient from the penalties was canceling out in the positive and negative phases of the gradient calculation.

fix penalty cancelation bug
